//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SOAPBasicAuthInjector.AR_GetOracleInvoiceNumber {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OracleInvoiceNumber_Oracleinovice_REQUEST_binding", Namespace="urn:GetOracleInvoiceNumber")]
    public partial class OracleInvoiceNumber_Oracleinovice_REQUEST : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOracleInvoiceNumberOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OracleInvoiceNumber_Oracleinovice_REQUEST() {
            this.Url = global::SOAPBasicAuthInjector.Properties.Settings.Default.SOAPBasicAuthInjector_AR_GetOracleInvoiceNumber_OracleInvoiceNumber_Oracleinovice_REQUEST;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOracleInvoiceNumberCompletedEventHandler GetOracleInvoiceNumberCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:GetOracleInvoiceNumber/GetOracleInvoiceNumber", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("OracleInvoiceNos", Namespace="http://gnp.pnmsoft_GetOracleInvoiceNumber.com")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public OracleInvoiceNo[] GetOracleInvoiceNumber([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://gnp.pnmsoft_GetOracleInvoiceNumber.com")] [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] PNMInvoiceNum[] PNMInvoiceNos) {
            object[] results = this.Invoke("GetOracleInvoiceNumber", new object[] {
                        PNMInvoiceNos});
            return ((OracleInvoiceNo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOracleInvoiceNumberAsync(PNMInvoiceNum[] PNMInvoiceNos) {
            this.GetOracleInvoiceNumberAsync(PNMInvoiceNos, null);
        }
        
        /// <remarks/>
        public void GetOracleInvoiceNumberAsync(PNMInvoiceNum[] PNMInvoiceNos, object userState) {
            if ((this.GetOracleInvoiceNumberOperationCompleted == null)) {
                this.GetOracleInvoiceNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOracleInvoiceNumberOperationCompleted);
            }
            this.InvokeAsync("GetOracleInvoiceNumber", new object[] {
                        PNMInvoiceNos}, this.GetOracleInvoiceNumberOperationCompleted, userState);
        }
        
        private void OnGetOracleInvoiceNumberOperationCompleted(object arg) {
            if ((this.GetOracleInvoiceNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOracleInvoiceNumberCompleted(this, new GetOracleInvoiceNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gnp.pnmsoft_GetOracleInvoiceNumber.com")]
    public partial class PNMInvoiceNum {
        
        private string pNMInvoiceNoField;
        
        private string eNTITY_NAMEField;
        
        private string bATCH_SOURCE_NAMEField;
        
        /// <remarks/>
        public string PNMInvoiceNo {
            get {
                return this.pNMInvoiceNoField;
            }
            set {
                this.pNMInvoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public string ENTITY_NAME {
            get {
                return this.eNTITY_NAMEField;
            }
            set {
                this.eNTITY_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string BATCH_SOURCE_NAME {
            get {
                return this.bATCH_SOURCE_NAMEField;
            }
            set {
                this.bATCH_SOURCE_NAMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gnp.pnmsoft_GetOracleInvoiceNumber.com")]
    public partial class OracleInvoiceNo {
        
        private string statusField;
        
        private string reasonField;
        
        private string interfaceLineAttribute1Field;
        
        private string oracleInvoiceNumberField;
        
        private double outstandingAmountField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public string InterfaceLineAttribute1 {
            get {
                return this.interfaceLineAttribute1Field;
            }
            set {
                this.interfaceLineAttribute1Field = value;
            }
        }
        
        /// <remarks/>
        public string OracleInvoiceNumber {
            get {
                return this.oracleInvoiceNumberField;
            }
            set {
                this.oracleInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public double OutstandingAmount {
            get {
                return this.outstandingAmountField;
            }
            set {
                this.outstandingAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetOracleInvoiceNumberCompletedEventHandler(object sender, GetOracleInvoiceNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOracleInvoiceNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOracleInvoiceNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OracleInvoiceNo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OracleInvoiceNo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591