//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPBasicAuthInjector.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genpacticsinstancedev01-a432914.integration.us2.oraclecloud.com:443/integ" +
            "ration/flowsvc/soap/SOAP_SERVICE/v01/")]
        public string SOAPBasicAuthInjector_GenPactUserInfo_EmpServicePort_GetUserName_REQUEST {
            get {
                return ((string)(this["SOAPBasicAuthInjector_GenPactUserInfo_EmpServicePort_GetUserName_REQUEST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genpacticsinstancedev01-a432914.integration.us2.oraclecloud.com:443/integ" +
            "ration/flowsvc/soap/PNMSOFT_AR_INVOICE_INTEGRAT/v01/")]
        public string SOAPBasicAuthInjector_AR_CreateInvoice_InoviceData_createInvoice_REQUEST {
            get {
                return ((string)(this["SOAPBasicAuthInjector_AR_CreateInvoice_InoviceData_createInvoice_REQUEST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genpacticsinstancedev01-a432914.integration.us2.oraclecloud.com:443/integ" +
            "ration/flowsvc/soap/PNMSOFT_AR_CREDIT_INTEGRATION/v01/")]
        public string SOAPBasicAuthInjector_AR_CreditNote_CreditNote_CreateCredit_REQUEST {
            get {
                return ((string)(this["SOAPBasicAuthInjector_AR_CreditNote_CreditNote_CreateCredit_REQUEST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genpacticsinstancedev01-a432914.integration.us2.oraclecloud.com:443/integ" +
            "ration/flowsvc/soap/PNMSOFTGETORACLE_INTEGRATION/v01/")]
        public string SOAPBasicAuthInjector_AR_GetOracleInvoiceNumber_OracleInvoiceNumber_Oracleinovice_REQUEST {
            get {
                return ((string)(this["SOAPBasicAuthInjector_AR_GetOracleInvoiceNumber_OracleInvoiceNumber_Oracleinovice" +
                    "_REQUEST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genpacticsinstancedev01-a432914.integration.us2.oraclecloud.com:443/integ" +
            "ration/flowsvc/soap/PNMSOFT_ORACLEINVO_INTEGRATIO/v01/")]
        public string SOAPBasicAuthInjector_AR_GetOutstandingAmount_GetInvoiceStatus_Invoice_Status_REQUEST {
            get {
                return ((string)(this["SOAPBasicAuthInjector_AR_GetOutstandingAmount_GetInvoiceStatus_Invoice_Status_REQ" +
                    "UEST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://genpacticsinstancedev01-a432914.integration.us2.oraclecloud.com:443/integ" +
            "ration/flowsvc/soap/PNMSOFT_AKRITIV_CREATECA_INTEGRA/v01/")]
        public string SOAPBasicAuthInjector_AP_CreateCase_Create_Case_From_PNMSoft_Akritiv_REQUESTPortType_CreateCase_REQUEST {
            get {
                return ((string)(this["SOAPBasicAuthInjector_AP_CreateCase_Create_Case_From_PNMSoft_Akritiv_REQUESTPortT" +
                    "ype_CreateCase_REQUEST"]));
            }
        }
    }
}
