//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SOAPBasicAuthInjector.AP_CreateCase {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Create_Case_From_PNMSoft_Akritiv_REQUESTPortType_CreateCase_REQUEST_binding", Namespace="urn:http://www.genpacticspnm/createcase.com")]
    public partial class Create_Case_From_PNMSoft_Akritiv_REQUESTPortType_CreateCase_REQUEST : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateCaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Create_Case_From_PNMSoft_Akritiv_REQUESTPortType_CreateCase_REQUEST() {
            this.Url = global::SOAPBasicAuthInjector.Properties.Settings.Default.SOAPBasicAuthInjector_AP_CreateCase_Create_Case_From_PNMSoft_Akritiv_REQUESTPortType_CreateCase_REQUEST;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCaseCompletedEventHandler CreateCaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:http://www.genpacticspnm/createcase.com/CreateCase", RequestElementName="CreateCaseRequest", RequestNamespace="http://www.genpacticspnmcc/XMLSchema.com", ResponseNamespace="http://www.genpacticspnmcc/XMLSchema.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Status")]
        public string CreateCase(Header Header, [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] LineItem[] LineItems, out string AkritivESMId, out string HeaderRecordId, out string UniqueRequestId, [System.Xml.Serialization.XmlElementAttribute("LineItemsRes")] out LineItemRes[] LineItemsRes, out string Message, out string Source, out string AkritivCaseStatus) {
            object[] results = this.Invoke("CreateCase", new object[] {
                        Header,
                        LineItems});
            AkritivESMId = ((string)(results[1]));
            HeaderRecordId = ((string)(results[2]));
            UniqueRequestId = ((string)(results[3]));
            LineItemsRes = ((LineItemRes[])(results[4]));
            Message = ((string)(results[5]));
            Source = ((string)(results[6]));
            AkritivCaseStatus = ((string)(results[7]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCaseAsync(Header Header, LineItem[] LineItems) {
            this.CreateCaseAsync(Header, LineItems, null);
        }
        
        /// <remarks/>
        public void CreateCaseAsync(Header Header, LineItem[] LineItems, object userState) {
            if ((this.CreateCaseOperationCompleted == null)) {
                this.CreateCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCaseOperationCompleted);
            }
            this.InvokeAsync("CreateCase", new object[] {
                        Header,
                        LineItems}, this.CreateCaseOperationCompleted, userState);
        }
        
        private void OnCreateCaseOperationCompleted(object arg) {
            if ((this.CreateCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCaseCompleted(this, new CreateCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.genpacticspnmcc/XMLSchema.com")]
    public partial class Header {
        
        private string sourceOfInvoiceField;
        
        private string documentTypeField;
        
        private string lECodeField;
        
        private string invoiceNumberField;
        
        private System.DateTime invoiceDateField;
        
        private string oHRIDField;
        
        private string supplierUniqueNoField;
        
        private string currencyField;
        
        private string paymentTermsField;
        
        private double taxesField;
        
        private bool taxesFieldSpecified;
        
        private double totalAmountField;
        
        private double amountField;
        
        private string invoiceDescriptionField;
        
        private string jobIdField;
        
        private string typeOfDocField;
        
        private string uniqueRequestIdField;
        
        private string sourceField;
        
        /// <remarks/>
        public string SourceOfInvoice {
            get {
                return this.sourceOfInvoiceField;
            }
            set {
                this.sourceOfInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string LECode {
            get {
                return this.lECodeField;
            }
            set {
                this.lECodeField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string OHRID {
            get {
                return this.oHRIDField;
            }
            set {
                this.oHRIDField = value;
            }
        }
        
        /// <remarks/>
        public string SupplierUniqueNo {
            get {
                return this.supplierUniqueNoField;
            }
            set {
                this.supplierUniqueNoField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string PaymentTerms {
            get {
                return this.paymentTermsField;
            }
            set {
                this.paymentTermsField = value;
            }
        }
        
        /// <remarks/>
        public double Taxes {
            get {
                return this.taxesField;
            }
            set {
                this.taxesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxesSpecified {
            get {
                return this.taxesFieldSpecified;
            }
            set {
                this.taxesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceDescription {
            get {
                return this.invoiceDescriptionField;
            }
            set {
                this.invoiceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
            }
        }
        
        /// <remarks/>
        public string TypeOfDoc {
            get {
                return this.typeOfDocField;
            }
            set {
                this.typeOfDocField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueRequestId {
            get {
                return this.uniqueRequestIdField;
            }
            set {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.genpacticspnmcc/XMLSchema.com")]
    public partial class LineItemRes {
        
        private string akritivESMLineIdField;
        
        private string akritivESMCostAllIdField;
        
        private string lineRecordIdField;
        
        private string costAllRecordIdField;
        
        private string messageField;
        
        private string successStatusField;
        
        /// <remarks/>
        public string AkritivESMLineId {
            get {
                return this.akritivESMLineIdField;
            }
            set {
                this.akritivESMLineIdField = value;
            }
        }
        
        /// <remarks/>
        public string AkritivESMCostAllId {
            get {
                return this.akritivESMCostAllIdField;
            }
            set {
                this.akritivESMCostAllIdField = value;
            }
        }
        
        /// <remarks/>
        public string LineRecordId {
            get {
                return this.lineRecordIdField;
            }
            set {
                this.lineRecordIdField = value;
            }
        }
        
        /// <remarks/>
        public string CostAllRecordId {
            get {
                return this.costAllRecordIdField;
            }
            set {
                this.costAllRecordIdField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string SuccessStatus {
            get {
                return this.successStatusField;
            }
            set {
                this.successStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.genpacticspnmcc/XMLSchema.com")]
    public partial class CostAllocation {
        
        private string costCodeField;
        
        private string projectNumberField;
        
        private string taskNumberField;
        
        private string expenditureOrganizationField;
        
        private string expenditureTypeField;
        
        /// <remarks/>
        public string CostCode {
            get {
                return this.costCodeField;
            }
            set {
                this.costCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProjectNumber {
            get {
                return this.projectNumberField;
            }
            set {
                this.projectNumberField = value;
            }
        }
        
        /// <remarks/>
        public string TaskNumber {
            get {
                return this.taskNumberField;
            }
            set {
                this.taskNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ExpenditureOrganization {
            get {
                return this.expenditureOrganizationField;
            }
            set {
                this.expenditureOrganizationField = value;
            }
        }
        
        /// <remarks/>
        public string ExpenditureType {
            get {
                return this.expenditureTypeField;
            }
            set {
                this.expenditureTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.genpacticspnmcc/XMLSchema.com")]
    public partial class LineLabel {
        
        private string invoiceLineNoField;
        
        private string akritivESMProductServiceDescriptionField;
        
        private double akritivESMRateField;
        
        private string commentField;
        
        /// <remarks/>
        public string InvoiceLineNo {
            get {
                return this.invoiceLineNoField;
            }
            set {
                this.invoiceLineNoField = value;
            }
        }
        
        /// <remarks/>
        public string AkritivESMProductServiceDescription {
            get {
                return this.akritivESMProductServiceDescriptionField;
            }
            set {
                this.akritivESMProductServiceDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public double AkritivESMRate {
            get {
                return this.akritivESMRateField;
            }
            set {
                this.akritivESMRateField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.genpacticspnmcc/XMLSchema.com")]
    public partial class LineItem {
        
        private LineLabel lineLabelField;
        
        private CostAllocation costAllocationField;
        
        private string uniqueRequestIdField;
        
        private string sourceField;
        
        /// <remarks/>
        public LineLabel LineLabel {
            get {
                return this.lineLabelField;
            }
            set {
                this.lineLabelField = value;
            }
        }
        
        /// <remarks/>
        public CostAllocation CostAllocation {
            get {
                return this.costAllocationField;
            }
            set {
                this.costAllocationField = value;
            }
        }
        
        /// <remarks/>
        public string UniqueRequestId {
            get {
                return this.uniqueRequestIdField;
            }
            set {
                this.uniqueRequestIdField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void CreateCaseCompletedEventHandler(object sender, CreateCaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string AkritivESMId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string HeaderRecordId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string UniqueRequestId {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public LineItemRes[] LineItemsRes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LineItemRes[])(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string AkritivCaseStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
    }
}

#pragma warning restore 1591